"""
Create workspace.otm.dq_alerts table
======================================
Stores alerts generated by the Monitor Agent (ST-6) when a KPI is RED or AMBER.
Each alert can be enriched with a root-cause analysis (ST-7) and a remediation
log entry (ST-8).

Usage:
    python create_dq_alerts_table.py
"""

import os
from databricks import sql
from dotenv import load_dotenv

load_dotenv()

conn = sql.connect(
    server_hostname=os.getenv("DATABRICKS_SERVER_HOSTNAME"),
    http_path=os.getenv("DATABRICKS_HTTP_PATH"),
    access_token=os.getenv("DATABRICKS_ACCESS_TOKEN"),
)
cursor = conn.cursor()

create_sql = """
CREATE TABLE IF NOT EXISTS workspace.otm.dq_alerts (
    alert_id          BIGINT GENERATED ALWAYS AS IDENTITY,
    created_at        TIMESTAMP,
    kpi_id            STRING,
    kpi_value         DOUBLE,
    target_value      DOUBLE,
    severity          STRING,          -- 'RED' or 'AMBER'
    message           STRING,          -- Bob's plain-English explanation
    recommendation    STRING,          -- Bob's suggested action
    status            STRING,          -- 'Open', 'In Review', 'Resolved'
    remediation_log   STRING,          -- SQL applied + timestamp (populated by ST-8)
    resolved_at       TIMESTAMP
)
"""

print("Creating table workspace.otm.dq_alerts ...")
cursor.execute(create_sql)
print("[SUCCESS] Table workspace.otm.dq_alerts created (or already exists)")

cursor.execute("SHOW TABLES IN workspace.otm")
rows = cursor.fetchall()
print(f"\nTables in workspace.otm ({len(rows)} total):")
print("-" * 40)
for r in rows:
    print(f"  - {r[1]}")

cursor.close()
conn.close()
